trigger: none

pool:
  name: 'Core Engineering'
    
stages:
- stage:  Build
  displayName : Build
  jobs:
  - deployment:
    displayName: 'Disable ExecutionRunner'
    environment: Build_Env
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Enable ExecutionRunner'
            inputs:
              azureSubscription: svc-5839-dmp-runway-build-d
              addSpnToEnvironment: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az functionapp config appsettings set \
                --name dmp-fnapp-runway-build-001 \
                --resource-group rg-DMPEnterpriseDataIngestion-build-001 \
                --settings AzureWebJobs.ExecutionRunner.Disabled=false
- stage:  Prod
  displayName : Prod
  dependsOn: Build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  jobs:
  - deployment:
    displayName: 'Disable ExecutionRunner'
    environment: Prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Enable ExecutionRunner'
            inputs:
              azureSubscription: svc-5839-dmp-runway-build-p
              addSpnToEnvironment: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az functionapp config appsettings set \
                --name dmp-fnapp-runway-prod-001 \
                --resource-group rg-DMPEnterpriseDataIngestion-prod-001 \
                --settings AzureWebJobs.ExecutionRunner.Disabled=false
