trigger: none

pool:
  name: 'Core Engineering'
    
stages:
- stage:  Build
  displayName : Build
  jobs:
  - deployment:
    displayName: 'Start functionapp'
    environment: Build_Env
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Start functionapp'
            inputs:
              azureSubscription: svc-5839-dmp-runway-build-d
              addSpnToEnvironment: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az functionapp start --id /subscriptions/60b60000-6cbd-4c1b-94b3-2440bd6bbe00/resourceGroups/rg-DMPEnterpriseDataIngestion-build-001/providers/Microsoft.Web/sites/dmp-fnapp-runway-build-001
- stage:  Prod
  displayName : Prod
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment:
    displayName: 'Start functionapp'
    environment: Prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Start functionapp'
            inputs:
              azureSubscription: svc-5839-dmp-runway-build-p
              addSpnToEnvironment: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az functionapp start --id /subscriptions/d4ed766d-813e-4037-b448-2d1dd7ef81f6/resourceGroups/rg-DMPEnterpriseDataIngestion-prod-001/providers/Microsoft.Web/sites/dmp-fnapp-runway-prod-001
